#!/bin/bash
#BSUB -J testRS6i5a
#BSUB -q cpu38      # this queue just contain cu39.
#BSUB -n 64
#BSUB -o test

nohup qr.refine 6i5a_box.ccp4  6i5a_box_complete.pdb  mode=refine  quantum.nproc=12 parallel.nproc=5  max_bond_rmsd=0.03  stpmax=0.2 gradient_only=true clustering=true use_convergence_test=true  opt_log=1 restraints=qm  engine_name=xtb quantum.method='--gfn 1 --gbsa h2o' > 6i5a_xtbgfn1_stpmax02_RSRClash.log 2>&1 &

